---
- name: gitlab
  hosts: gitlab
  tags:
    - gitlab

  pre_tasks:
    - name: apt update
      ansible.builtin.apt:
        update_cache: true
  
  tasks:
    - name: Install pre-package
      ansible.builtin.package:
        name: curl
        state: present

    - name: Download gitlab install
      ansible.builtin.get_url:
        url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
        dest: /tmp/gitlab.sh
        mode: '0550'

    - name: Exec gitlab install
      ansible.builtin.shell: bash /tmp/gitlab.sh
        
    - name: Install gitlab
      ansible.builtin.package:
        name: gitlab-ce=16.7.0-ce.0
        state: present
      environment:
        GITLAB_ROOT_PASSWORD: "{{gitlab_root_pass}}"
        EXTERNAL_URL: "{{gitlab_external_url}}"

    - name: Install nfs-server
      ansible.builtin.package:
        name: nfs-kernel-server
        state: present
      tags: nfs

    - name: Create nfs directory
      ansible.builtin.file:
        path: "{{ nfs_dir }}"
        state: directory
        mode: '0755'
      tags: nfs

    - name: Create /etc/exports
      ansible.builtin.template:
        src: templates/nfs/exports.j2
        dest: /etc/exports
      tags: nfs

    - name: Restart service nfs
      ansible.builtin.service:
        name: nfs-kernel-server
        state: restarted
      tags: nfs
